# Generated by Django 4.2.28 on 2026-02-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('block', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('probability', models.IntegerField(help_text='Вероятность в %')),
                ('severity', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], default='medium', max_length=10)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ClassRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('current_kwh', models.FloatField()),
                ('previous_kwh', models.FloatField()),
                ('savings_percent', models.FloatField()),
                ('trees_saved', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-savings_percent'],
            },
        ),
        migrations.CreateModel(
            name='EnergyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('block', models.CharField(default='Блок А', max_length=50)),
                ('kwh', models.FloatField()),
                ('cost_tenge', models.FloatField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
